### ISSUE TITLE
unable to resolve symbol  new UltrasonicModule() from class PackageList

### ISSUE THREAD

**Issue by kanikas24** [assemmohamedali/react-native-ultrasonic#1]
Even after downgrading the gradle, the error doesnt seems to change. What can be the possible solution you can suggest?

Project developed using command react-native init 
Done all installations as per the documentation.
**Error:**
Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
/Users/MobileApplication/Desktop/AwesomeProject1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: cannot find symbol
      new UltrasonicModule()
          ^
  symbol:   class UltrasonicModule
  location: class PackageList
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by kanikas24** [comment]
Hey,
Solved it by unlinking the library (npm unlink react-native-ultrasonic)
If that doesn't work, try installing rnpm.
Amazing library!!
Well done @assemmohamedali 
Thanks

**Comment by kanikas24** [comment]
The problem came again. It's better if @assemmohamedali suggest some solution. I even tried cloning your mentioned example but its not supporting the latest gradle.

**Comment by aboozaid** [comment]
Did you import the package before passing it?
